paths:
  baseline: "/home/pgliwny/Praca/Computer_vision_for_MAGIC/data/baseline/baseline_webcam_features.h5"
  img_path_dir: "/home/pgliwny/Praca/Computer_vision_for_MAGIC/data/data/webcam_img/"
  calib: "/home/pgliwny/Praca/Computer_vision_for_MAGIC/data/calibration/points_WebCam.json"
  test_img: "/home/pgliwny/Praca/Computer_vision_for_MAGIC/data/annotations/img_with_annomarly.json"