paths:
  baseline: "/media/pgliwny/ADATA HD3303/Computer_Vision_system/data/baseline/baseline_webcam_features.h5"
  img_path: "/media/pgliwny/ADATA HD3303/Computer_Vision_system/data/MAGIC/webcam_useful_images/image_2024-05-12_1000.jpg"
  calib: "/media/pgliwny/ADATA HD3303/Computer_Vision_system/data/points_WebCam.json"

